import '../globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

// import { AppSidebar } from '@/components/app-sidebar';
import Footer from '@/components/navigation/footer/footer';
import TopNavigation from '@/components/navigation/top_navigation/top-navigation';
// import {
// 	Breadcrumb,
// 	BreadcrumbItem,
// 	BreadcrumbLink,
// 	BreadcrumbList,
// 	BreadcrumbPage,
// 	BreadcrumbSeparator,
// } from '@/components/ui/breadcrumb';
// import { Separator } from '@/components/ui/separator';
// import {
// 	SidebarInset,
// 	SidebarProvider,
// 	SidebarTrigger,
// } from '@/components/ui/sidebar';

const geistSans = localFont({
	src: '../fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: '../fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} grid grid-cols-1 antialiased`}
			>
				<TopNavigation />
				<main
					role="main"
					className="flex w-full flex-col items-start justify-start xl:container xl:mx-auto"
				>
					{children}
				</main>
				<Footer />
			</body>
		</html>
	);
}

//
// {/*<SidebarProvider className={'rounded-[30px] overflow-hidden'}>*/}
// {/*	<AppSidebar />*/}
// {/*	<SidebarInset className={'bg-[#b3eabc] rounded-[30px] overflow-hidden'}>*/}
// {/*		<main className={'rounded-[30px] overflow-hidden'}>*/}
// {/*			<SidebarTrigger />*/}
// {/*			{children}*/}
//
// {/*			/!*<AppSidebar />*!/*/}
// {/*		</main>*/}
// {/*	</SidebarInset>*/}
// {/*</SidebarProvider>*/}
